formater: --color --format pretty

reports: -f progress --format html --out reports/execution_report.html

default: -f json -o execution_log.json -x -f rerun -o cucumber_failures.txt

rerun: -f json -o execution_log_rerun.json -x

all_tags: --tag @content,@service

content: --tag @content

services: --tag @service BROWSER=pg